### ISSUE TITLE
YouTube: Allow fetching more than 50 items

### ISSUE THREAD

**Issue by madiele** [amckee/PodTube#20]
Hi i've got an issue on my repo about raising the item limit from 50 (the limit for a single YouTube API call)

https://github.com/madiele/vod2pod-rss/issues/90

I've given a look at the code and it seems there is already some kinda of logic for it but it was manually disabled with this line `response = {'nextPageToken': ''}` before the loop for both channels and playlist

I guess maybe to prevent fetching 3000+ videos accidentally on big channels, do you thing is possible to re-implement the feature back-in some way?

If you want I can open a PR myself too, just tell me what is your preferred solution and I'll code something as soon as I have a spare weekend✌️

**Comment by amckee** [comment]
Admittedly, my understanding of the Youtube code is lacking since it was written by @aquacash5 that I forked from, though after doing some poking around with this I believe that the code pulls the first 50 results, then if those results include a 'nextPageToken' key, it pulls the next page:

https://github.com/amckee/PodTube/blob/7d9128b19e5e8a93caaafb8593b7368e5cc0d50a/youtube.py#L322C17-L322C17

I've created a branch (https://github.com/amckee/PodTube/tree/Issue20) that includes extra logging in this regard, reporting the number of items and pages that a channel request results in:

`2023-08-11 18:23:01,271 [INFO] Got 52 videos from 3 pages`

**Comment by aquacash5** [comment]
You might have some luck with this alternate API https://developers.google.com/youtube/v3/docs/channels/list. I haven't tested it, but it looks like it could be a drop-in replacement.
